#!/usr/bin/env bash
# Start everything for local development with one command:
#
#   scripts/dev.sh              # (or: make dev / npm run dev / pnpm dev)
#   scripts/dev.sh --kill-ports # first stop whatever is holding ports 3000 / 8000
#   scripts/dev.sh --stop-db    # also stop Postgres + Redis when you press Ctrl-C
#
# Steps: check tools -> env files -> dependencies (only when changed) -> Postgres + Redis -> migrations
#        -> instrument refresh
#        -> API (:8000) + web (:3000) with prefixed logs -> wait until both answer -> Ctrl-C stops both.
set -euo pipefail
cd "$(dirname "$0")/.."
ROOT=$PWD

API_PORT=8000
WEB_PORT=3000
KILL_PORTS=0
STOP_DB=0
for arg in "$@"; do
  case "$arg" in
    --kill-ports) KILL_PORTS=1 ;;
    --stop-db) STOP_DB=1 ;;
    -h|--help) sed -n '2,10p' "$0"; exit 0 ;;
    *) echo "unknown option: $arg (see --help)"; exit 2 ;;
  esac
done

bold=$'\033[1m'; dim=$'\033[2m'; red=$'\033[31m'; green=$'\033[32m'; yellow=$'\033[33m'; blue=$'\033[34m'
magenta=$'\033[35m'; reset=$'\033[0m'
step() { echo "${bold}${blue}==>${reset} ${bold}$*${reset}"; }
ok() { echo "    ${green}✓${reset} $*"; }
warn() { echo "    ${yellow}!${reset} $*"; }
die() { echo "    ${red}✗ $*${reset}" >&2; exit 1; }

# -- 1. tools ------------------------------------------------------------------------------------------
step "Checking tools"
need() { command -v "$1" >/dev/null 2>&1 || die "$1 is not installed. $2"; }
need node "Install Node 22+ (e.g. brew install node@22)."
need pnpm "Install it with: brew install pnpm"
need uv "Install it with: brew install uv"
node_major=$(node -p 'process.versions.node.split(".")[0]')
[ "$node_major" -ge 22 ] || die "Node $node_major found; Node 22+ is required."
if ! command -v redis-server >/dev/null 2>&1 || ! brew --prefix postgresql@17 >/dev/null 2>&1; then
  die "Postgres 17 / Redis not found. Install them with: brew install postgresql@17 redis"
fi
ok "node $(node -v), pnpm $(pnpm -v), $(uv --version | cut -d' ' -f1-2)"

# -- 2. env files --------------------------------------------------------------------------------------
step "Checking configuration"
if [ ! -f .env ]; then
  cp .env.example .env && chmod 600 .env
  warn "created .env from .env.example: add your Clerk keys to it"
fi
if [ ! -f apps/web/.env.local ]; then
  cp apps/web/.env.example apps/web/.env.local && chmod 600 apps/web/.env.local
  warn "created apps/web/.env.local from its example: add your Clerk keys to it"
fi
has_value() { grep -Eq "^$1=.+" "$2"; }
if ! has_value APP_ENCRYPTION_KEY .env; then
  key=$(python3 -c 'import base64, os; print(base64.b64encode(os.urandom(32)).decode())')
  sed -i.bak '/^APP_ENCRYPTION_KEY=/d' .env && rm -f .env.bak
  printf '\n# Master key for broker credentials (generated by scripts/dev.sh). Keep it safe; never commit it.\nAPP_ENCRYPTION_KEY=%s\n' "$key" >> .env
  ok "generated APP_ENCRYPTION_KEY in .env"
fi
for f in "CLERK_PUBLISHABLE_KEY .env" "CLERK_SECRET_KEY .env" \
         "NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY apps/web/.env.local" "CLERK_SECRET_KEY apps/web/.env.local"; do
  set -- $f
  has_value "$1" "$2" || warn "$1 is empty in $2: sign-in will not work until it is set"
done
ok "env files present (values not shown)"

# -- 3. dependencies (only when the lockfiles changed) ------------------------------------------------
step "Checking dependencies"
stamp=.data/.deps-stamp
mkdir -p .data
current=$(cat pnpm-lock.yaml uv.lock | shasum | cut -d' ' -f1)
if [ ! -d node_modules ] || [ ! -d .venv ] || [ "$(cat "$stamp" 2>/dev/null)" != "$current" ]; then
  echo "    installing (lockfiles changed or first run)..."
  pnpm install --frozen-lockfile --silent || die "pnpm install failed (see above)"
  uv sync --all-packages --frozen --quiet || die "uv sync failed (see above)"
  echo "$current" > "$stamp"
  ok "dependencies installed"
else
  ok "up to date"
fi

# -- 4. ports -------------------------------------------------------------------------------------------
# the home production stack (scripts/home-host.sh) uses the same database: two engines would trade twice
if launchctl print "gui/$(id -u)/com.algoearning.engine" >/dev/null 2>&1; then
  die "the production services are running (scripts/home-host.sh status). Stop them first: scripts/home-host.sh stop"
fi
step "Checking ports $WEB_PORT and $API_PORT"
for port in "$WEB_PORT" "$API_PORT"; do
  pids=$(lsof -nP -tiTCP:"$port" -sTCP:LISTEN 2>/dev/null || true)
  [ -z "$pids" ] && continue
  who=$(ps -o pid=,command= -p $(echo $pids | tr ' ' ',') | cut -c1-110)
  if [ "$KILL_PORTS" = 1 ]; then
    kill $pids 2>/dev/null || true
    sleep 1
    ok "stopped what was using port $port"
  else
    die "port $port is already in use by:
$who
      Stop it, or run: scripts/dev.sh --kill-ports"
  fi
done
ok "free"

# -- 5. database + cache ----------------------------------------------------------------------------------
step "Starting Postgres + Redis"
scripts/local-db.sh up | sed 's/^/    /'

step "Applying database migrations"
DATABASE_URL=$(grep -E '^DATABASE_URL=' .env | cut -d= -f2- || true)
DATABASE_URL=${DATABASE_URL:-postgresql://algoearning:algoearning@localhost:5432/algoearning}
DATABASE_URL=$DATABASE_URL uv run alembic -c packages/py-db/alembic.ini upgrade head 2>&1 |
  grep -E "Running upgrade|ERROR|Error" | sed 's/^/    /' || true
ok "database schema is current"

step "Refreshing instruments (lot sizes, strike steps, expiries) from Zerodha"
if DATABASE_URL=$DATABASE_URL uv run python -m ae_worker refresh-instruments >/dev/null 2>&1; then
  ok "instruments are current"
else
  warn "could not refresh instruments (offline?): using the last known values"
fi

# -- 6. API + web -----------------------------------------------------------------------------------------
step "Starting API and web"
pids=()
descendants() { # every process below $1, deepest first
  local child
  for child in $(pgrep -P "$1" 2>/dev/null); do descendants "$child"; echo "$child"; done
}
cleanup() {
  trap - INT TERM EXIT
  echo
  step "Stopping"
  # The servers run a few levels down (subshell -> uv/pnpm -> uvicorn reloader -> worker, next -> next-server):
  # stop the whole tree, not just our direct children, so nothing is left holding ports 3000/8000.
  local tree
  tree=$(descendants $$)
  [ -n "$tree" ] && kill -TERM $tree 2>/dev/null || true
  for _ in 1 2 3 4 5 6 7 8 9 10; do
    tree=$(descendants $$)
    [ -z "$tree" ] && break
    sleep 0.5
  done
  [ -n "$tree" ] && kill -KILL $tree 2>/dev/null || true
  wait 2>/dev/null || true
  if [ "$STOP_DB" = 1 ]; then scripts/local-db.sh down | sed 's/^/    /'; else echo "    Postgres + Redis left running (stop them with: make db-down)"; fi
  ok "stopped"
}
trap cleanup INT TERM EXIT

prefix() { # prefix every line of a process's output, unbuffered
  awk -v p="$1" '{ print p $0; fflush() }'
}

( uv run --env-file .env uvicorn ae_api.main:app --reload --port "$API_PORT" \
    --reload-dir apps/api/src --reload-dir packages 2>&1 | prefix "${magenta}api ${reset}│ " ) &
pids+=($!)
( pnpm --filter @algoearning/web exec next dev --port "$WEB_PORT" 2>&1 | prefix "${blue}web ${reset}│ " ) &
pids+=($!)
# the platform price feed: Breeze when BREEZE_API_KEY/SECRET are set in .env, simulated prices otherwise
( uv run --env-file .env python -m ae_marketdata 2>&1 | prefix "${yellow}feed${reset}│ " ) &
pids+=($!)
# the worker: sends notifications, links Telegram, raises the engine-down alert, refreshes instruments daily
( uv run --env-file .env python -m ae_worker 2>&1 | prefix "${magenta}wrk ${reset}│ " ) &
pids+=($!)
# the trading engine: steps every deployed strategy (paper) every second
( uv run --env-file .env python -m ae_engine 2>&1 | prefix "${green}eng ${reset}│ " ) &
pids+=($!)

wait_for() { # url name seconds
  for _ in $(seq 1 "$3"); do
    curl -s -o /dev/null --max-time 2 "$1" && return 0
    sleep 1
  done
  return 1
}
wait_for "http://localhost:$API_PORT/health" API 60 || die "API did not start: see the 'api │' lines above"
wait_for "http://localhost:$WEB_PORT/" web 120 || die "web did not start: see the 'web │' lines above"

cat <<EOF

${bold}${green}AlgoEarning is running${reset}
  Web app     ${bold}http://localhost:$WEB_PORT${reset}
  API docs    http://localhost:$API_PORT/docs
  API health  http://localhost:$API_PORT/health/ready
  Monitor     http://localhost:$WEB_PORT/monitor (admins; market data under Market data)
  ${dim}Code changes reload automatically (restart for feed/engine changes). Ctrl-C stops the API, web, feed and engine$( [ "$STOP_DB" = 1 ] && echo ", Postgres and Redis").${reset}

EOF
wait
