"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-29 19:20:58.611145+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from ae_db import rls
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plans",
        sa.Column("code", sa.String(length=40), nullable=False),
        sa.Column("name", sa.String(length=80), nullable=False),
        sa.Column("price_paise", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "interval",
            sa.Enum("month", "year", name="plan_interval", native_enum=False, create_constraint=True, length=20),
            nullable=False,
        ),
        sa.Column("features", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("provider_plan_id", sa.String(length=100), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_plans")),
        sa.UniqueConstraint("code", name=op.f("uq_plans_code")),
        sa.UniqueConstraint("provider_plan_id", name=op.f("uq_plans_provider_plan_id")),
    )
    op.create_table(
        "users",
        sa.Column("auth_subject", sa.String(length=191), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("avatar_url", sa.String(length=1000), nullable=True),
        sa.Column(
            "role",
            sa.Enum("user", "admin", name="user_role", native_enum=False, create_constraint=True, length=20),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "suspended",
                "deleted",
                name="user_status",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("auth_subject", name=op.f("uq_users_auth_subject")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_table(
        "webhook_events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("event_id", sa.String(length=120), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_webhook_events")),
        sa.UniqueConstraint("provider", "event_id", name=op.f("uq_webhook_events_provider_event_id")),
    )
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("actor", sa.String(length=40), nullable=False),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("target_type", sa.String(length=40), nullable=True),
        sa.Column("target_id", sa.String(length=64), nullable=True),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.Column("user_agent", sa.String(length=400), nullable=True),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_audit_log_user_id_users"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_user_id"), "audit_log", ["user_id"], unique=False)
    op.create_table(
        "broker_accounts",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "broker",
            sa.Enum(
                "zerodha", "upstox", "angelone", name="broker", native_enum=False, create_constraint=True, length=20
            ),
            nullable=False,
        ),
        sa.Column("client_id", sa.String(length=40), nullable=False),
        sa.Column("label", sa.String(length=80), nullable=True),
        sa.Column("api_key_enc", sa.LargeBinary(), nullable=True),
        sa.Column("api_secret_enc", sa.LargeBinary(), nullable=True),
        sa.Column("key_version", sa.Integer(), nullable=False),
        sa.Column("static_ip", postgresql.INET(), nullable=True),
        sa.Column("terminal_enabled", sa.Boolean(), nullable=False),
        sa.Column("engine_enabled", sa.Boolean(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "disconnected",
                "connected",
                "expired",
                "error",
                name="broker_account_status",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("last_login_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_broker_accounts_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_broker_accounts")),
        sa.UniqueConstraint("user_id", "broker", "client_id", name=op.f("uq_broker_accounts_user_id_broker_client_id")),
    )
    op.create_index(op.f("ix_broker_accounts_user_id"), "broker_accounts", ["user_id"], unique=False)
    op.create_table(
        "strategies",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=120), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("kind", sa.String(length=40), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "ready",
                "archived",
                name="strategy_status",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_strategies_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_strategies")),
    )
    op.create_index("ix_strategies_user_created", "strategies", ["user_id", "created_at", "id"], unique=False)
    op.create_index(op.f("ix_strategies_user_id"), "strategies", ["user_id"], unique=False)
    op.create_table(
        "subscriptions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "active",
                "pending",
                "past_due",
                "cancelled",
                "expired",
                name="subscription_status",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("provider_subscription_id", sa.String(length=100), nullable=True),
        sa.Column("current_period_start", sa.DateTime(timezone=True), nullable=True),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cancel_at_period_end", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"], ["plans.id"], name=op.f("fk_subscriptions_plan_id_plans"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_subscriptions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_subscriptions")),
        sa.UniqueConstraint("provider_subscription_id", name=op.f("uq_subscriptions_provider_subscription_id")),
    )
    op.create_index(op.f("ix_subscriptions_user_id"), "subscriptions", ["user_id"], unique=False)
    op.create_table(
        "broker_sessions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("broker_account_id", sa.Uuid(), nullable=False),
        sa.Column("access_token_enc", sa.LargeBinary(), nullable=False),
        sa.Column("key_version", sa.Integer(), nullable=False),
        sa.Column("issued_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["broker_account_id"],
            ["broker_accounts.id"],
            name=op.f("fk_broker_sessions_broker_account_id_broker_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_broker_sessions_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_broker_sessions")),
        sa.UniqueConstraint("broker_account_id", name=op.f("uq_broker_sessions_broker_account_id")),
    )
    op.create_index(op.f("ix_broker_sessions_user_id"), "broker_sessions", ["user_id"], unique=False)
    op.create_table(
        "payments",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("subscription_id", sa.Uuid(), nullable=True),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("provider_payment_id", sa.String(length=100), nullable=False),
        sa.Column("amount_paise", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_payments_subscription_id_subscriptions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_payments_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payments")),
        sa.UniqueConstraint("provider_payment_id", name=op.f("uq_payments_provider_payment_id")),
    )
    op.create_index(op.f("ix_payments_user_id"), "payments", ["user_id"], unique=False)
    op.create_table(
        "strategy_runs",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("strategy_id", sa.Uuid(), nullable=False),
        sa.Column("broker_account_id", sa.Uuid(), nullable=True),
        sa.Column(
            "mode",
            sa.Enum("paper", "live", name="trading_mode", native_enum=False, create_constraint=True, length=20),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "stopping",
                "stopped",
                "completed",
                "error",
                name="run_status",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("config_snapshot", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("stopped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("realized_pnl", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["broker_account_id"],
            ["broker_accounts.id"],
            name=op.f("fk_strategy_runs_broker_account_id_broker_accounts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["strategy_id"], ["strategies.id"], name=op.f("fk_strategy_runs_strategy_id_strategies"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_strategy_runs_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_strategy_runs")),
    )
    op.create_index(op.f("ix_strategy_runs_strategy_id"), "strategy_runs", ["strategy_id"], unique=False)
    op.create_index(op.f("ix_strategy_runs_user_id"), "strategy_runs", ["user_id"], unique=False)
    op.create_table(
        "trades",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("broker_account_id", sa.Uuid(), nullable=True),
        sa.Column(
            "mode",
            sa.Enum("paper", "live", name="trading_mode", native_enum=False, create_constraint=True, length=20),
            nullable=False,
        ),
        sa.Column("status", sa.String(length=40), nullable=False),
        sa.Column("trade_date", sa.Date(), nullable=False),
        sa.Column("underlying", sa.String(length=30), nullable=False),
        sa.Column("exchange", sa.String(length=10), nullable=False),
        sa.Column("tradingsymbol", sa.String(length=60), nullable=False),
        sa.Column("expiry", sa.Date(), nullable=False),
        sa.Column("strike", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("option_type", sa.String(length=2), nullable=False),
        sa.Column(
            "side",
            sa.Enum("BUY", "SELL", name="side", native_enum=False, create_constraint=True, length=20),
            nullable=False,
        ),
        sa.Column("product", sa.String(length=10), nullable=False),
        sa.Column("lots", sa.Integer(), nullable=False),
        sa.Column("lot_size", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("entry_price", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("entry_avg_price", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("initial_sl", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("current_sl", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("target", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("filled_qty", sa.Integer(), nullable=False),
        sa.Column("exited_qty", sa.Integer(), nullable=False),
        sa.Column("open_qty", sa.Integer(), nullable=False),
        sa.Column("realized_pnl", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("unrealized_pnl", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("last_ltp", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("rules", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("exit_reason", sa.String(length=40), nullable=True),
        sa.Column("exit_avg_price", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("entry_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("exit_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["broker_account_id"],
            ["broker_accounts.id"],
            name=op.f("fk_trades_broker_account_id_broker_accounts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["run_id"], ["strategy_runs.id"], name=op.f("fk_trades_run_id_strategy_runs"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_trades_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trades")),
    )
    op.create_index(op.f("ix_trades_run_id"), "trades", ["run_id"], unique=False)
    op.create_index("ix_trades_user_date", "trades", ["user_id", "trade_date"], unique=False)
    op.create_index(op.f("ix_trades_user_id"), "trades", ["user_id"], unique=False)
    op.create_table(
        "orders",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("trade_id", sa.Uuid(), nullable=False),
        sa.Column("broker_account_id", sa.Uuid(), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "ENTRY",
                "SL",
                "TARGET",
                "PARTIAL",
                "EXIT",
                name="order_kind",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("tag", sa.String(length=20), nullable=False),
        sa.Column("broker_order_id", sa.String(length=60), nullable=True),
        sa.Column(
            "side",
            sa.Enum("BUY", "SELL", name="side", native_enum=False, create_constraint=True, length=20),
            nullable=False,
        ),
        sa.Column("order_type", sa.String(length=10), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("price", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("trigger_price", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column("filled_qty", sa.Integer(), nullable=False),
        sa.Column("avg_price", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("status_message", sa.Text(), nullable=True),
        sa.Column("reprices", sa.Integer(), nullable=False),
        sa.Column("modifications", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["broker_account_id"],
            ["broker_accounts.id"],
            name=op.f("fk_orders_broker_account_id_broker_accounts"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["trade_id"], ["trades.id"], name=op.f("fk_orders_trade_id_trades"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_orders_user_id_users"), ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
        sa.UniqueConstraint(
            "broker_account_id", "broker_order_id", name=op.f("uq_orders_broker_account_id_broker_order_id")
        ),
        sa.UniqueConstraint("tag", name=op.f("uq_orders_tag")),
    )
    op.create_index(op.f("ix_orders_trade_id"), "orders", ["trade_id"], unique=False)
    op.create_index(op.f("ix_orders_user_id"), "orders", ["user_id"], unique=False)
    op.create_table(
        "trade_events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("trade_id", sa.Uuid(), nullable=True),
        sa.Column("run_id", sa.Uuid(), nullable=True),
        sa.Column("event", sa.String(length=60), nullable=False),
        sa.Column("level", sa.String(length=10), nullable=False),
        sa.Column("from_status", sa.String(length=40), nullable=True),
        sa.Column("to_status", sa.String(length=40), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["run_id"], ["strategy_runs.id"], name=op.f("fk_trade_events_run_id_strategy_runs"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["trade_id"], ["trades.id"], name=op.f("fk_trade_events_trade_id_trades"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_trade_events_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trade_events")),
    )
    op.create_index(op.f("ix_trade_events_trade_id"), "trade_events", ["trade_id"], unique=False)
    op.create_index(op.f("ix_trade_events_user_id"), "trade_events", ["user_id"], unique=False)
    # ### end Alembic commands ###

    # Row-level security, roles, append-only audit log (see ae_db/rls.py).
    for stmt in rls.upgrade_sql():
        op.execute(stmt)

    # The always-available plan. Paid plans and the feature matrix arrive in phase 5.
    op.execute(
        "INSERT INTO plans (code, name, price_paise, currency, interval, features, is_active, sort_order) VALUES "
        "('free', 'Free', 0, 'INR', 'month', "
        """'{"live_trading": false, "paper_trading": true, "max_strategies": 5, "max_broker_accounts": 1}', true, 0)"""
    )


def downgrade() -> None:
    for stmt in rls.downgrade_sql():
        op.execute(stmt)
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_trade_events_user_id"), table_name="trade_events")
    op.drop_index(op.f("ix_trade_events_trade_id"), table_name="trade_events")
    op.drop_table("trade_events")
    op.drop_index(op.f("ix_orders_user_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_trade_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_trades_user_id"), table_name="trades")
    op.drop_index("ix_trades_user_date", table_name="trades")
    op.drop_index(op.f("ix_trades_run_id"), table_name="trades")
    op.drop_table("trades")
    op.drop_index(op.f("ix_strategy_runs_user_id"), table_name="strategy_runs")
    op.drop_index(op.f("ix_strategy_runs_strategy_id"), table_name="strategy_runs")
    op.drop_table("strategy_runs")
    op.drop_index(op.f("ix_payments_user_id"), table_name="payments")
    op.drop_table("payments")
    op.drop_index(op.f("ix_broker_sessions_user_id"), table_name="broker_sessions")
    op.drop_table("broker_sessions")
    op.drop_index(op.f("ix_subscriptions_user_id"), table_name="subscriptions")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_strategies_user_id"), table_name="strategies")
    op.drop_index("ix_strategies_user_created", table_name="strategies")
    op.drop_table("strategies")
    op.drop_index(op.f("ix_broker_accounts_user_id"), table_name="broker_accounts")
    op.drop_table("broker_accounts")
    op.drop_index(op.f("ix_audit_log_user_id"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_table("webhook_events")
    op.drop_table("users")
    op.drop_table("plans")
    # ### end Alembic commands ###
