"""prepaid billing orders

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-30 02:37:21.108085+00:00
"""

from collections.abc import Sequence

import sqlalchemy as sa
from ae_db import rls
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0003"
down_revision: str | None = "0002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "billing_orders",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("plan_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("provider_order_id", sa.String(length=60), nullable=False),
        sa.Column("amount_paise", sa.Integer(), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "created",
                "paid",
                "failed",
                name="billing_order_status",
                native_enum=False,
                create_constraint=True,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("provider_payment_id", sa.String(length=60), nullable=True),
        sa.Column("paid_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("subscription_id", sa.Uuid(), nullable=True),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_id"], ["plans.id"], name=op.f("fk_billing_orders_plan_id_plans"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["subscription_id"],
            ["subscriptions.id"],
            name=op.f("fk_billing_orders_subscription_id_subscriptions"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_billing_orders_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_billing_orders")),
        sa.UniqueConstraint("provider_order_id", name=op.f("uq_billing_orders_provider_order_id")),
        sa.UniqueConstraint("provider_payment_id", name=op.f("uq_billing_orders_provider_payment_id")),
    )
    op.create_index(op.f("ix_billing_orders_user_id"), "billing_orders", ["user_id"], unique=False)
    op.add_column(
        "subscriptions",
        sa.Column(
            "kind",
            sa.Enum("prepaid", "recurring", name="billing_kind", native_enum=False, create_constraint=True, length=20),
            server_default="prepaid",
            nullable=False,
        ),
    )
    # ### end Alembic commands ###

    for stmt in rls.table_sql("billing_orders"):
        op.execute(stmt)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("subscriptions", "kind")
    op.drop_index(op.f("ix_billing_orders_user_id"), table_name="billing_orders")
    op.drop_table("billing_orders")
    # ### end Alembic commands ###
